apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "surreal-dbops.fullname" . }}
  labels:
    {{- include "surreal-dbops.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "surreal-dbops.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "surreal-dbops.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "surreal-dbops.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ENABLE_WEBHOOK
              value: {{ .Values.webhook.enabled | quote }}
            - name: WEBHOOK_PORT
              value: {{ .Values.webhook.port | quote }}
            - name: TLS_CERT_PATH
              value: "/tls/tls.crt"
            - name: TLS_KEY_PATH
              value: "/tls/tls.key"
            - name: RUST_LOG
              value: "info"
          ports:
            {{- if .Values.webhook.enabled }}
            - name: webhook
              containerPort: {{ .Values.webhook.port }}
              protocol: TCP
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.webhook.enabled }}
          volumeMounts:
            - name: tls
              mountPath: /tls
              readOnly: true
          {{- end }}
      {{- if .Values.webhook.enabled }}
      volumes:
        - name: tls
          secret:
            secretName: {{ .Values.webhook.secretName }}
            defaultMode: 420
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
